export const CREATE_EVENT = 'CREATE_EVENT';

export const ADD_FOOD_TO_EVENT = 'ADD_FOOD_TO_EVENT';

export const INVITE_PEOPLE = 'INVITE_PEOPLE';

export const VIEW_ATTENDEES = 'VIEW_ATTENDEES';

export const LOAD_EVENTS_HOSTING = 'LOAD_EVENTS_HOSTING';
