export const CREATE_EVENT = 'CREATE_EVENT';
export const ADD_FOOD_TO_EVENT = 'ADD_FOOD_TO_EVENT';
export const INVITE_PEOPLE = 'INVITE_PEOPLE';
export const VIEW_ATTENDEES = 'VIEW_ATTENDEES';
export const LOAD_EVENTS_HOSTING = 'LOAD_EVENTS_HOSTING';
export const LOAD_EVENTS_INVITED = 'LOAD_EVENTS_INVITED';
export const FETCH_USER = 'FETCH_USER';
export const LIST_RSVP_YES = 'LIST_RSVP_YES';
